apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/build-id: "3"
    fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/3
    fabric8.io/git-branch: release-v2.2.265
    fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus/src/main/fabric8/icon.png
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=prometheus&var-version=2.2.265
  creationTimestamp: null
  generation: 1
  labels:
    group: io.fabric8.devops.apps
    project: prometheus
    provider: fabric8
    version: 2.2.265
  name: prometheus
spec:
  replicas: 1
  selector:
    group: io.fabric8.devops.apps
    project: prometheus
    provider: fabric8
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 10800
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/build-id: "3"
        fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/3
        fabric8.io/git-branch: release-v2.2.265
        fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus/src/main/fabric8/icon.png
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=prometheus&var-version=2.2.265
      creationTimestamp: null
      labels:
        group: io.fabric8.devops.apps
        project: prometheus
        provider: fabric8
        version: 2.2.265
    spec:
      containers:
      - args:
        - -config.file=/etc/prometheus/config/prometheus.yml
        - -storage.local.path=/prometheus
        - -web.console.libraries=/etc/prometheus/console_libraries
        - -web.console.templates=/etc/prometheus/consoles
        image: prom/prometheus:v1.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: prometheus
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config-volume
        - mountPath: /prometheus
          name: data-volume
      - args:
        - -volume-dir
        - /etc/prometheus/config
        - -webhook-url
        - http://localhost:9090/-/reload
        image: jimmidyson/configmap-reload:v0.1
        imagePullPolicy: IfNotPresent
        name: configmap-reload
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: metrics
      serviceAccountName: metrics
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: prometheus
        name: config-volume
      - emptyDir: {}
        name: data-volume
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 1
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
